CI: Fix check html failure (#195)
* CI: Update check on failed HTML file

* CI: Fix dependencies handling

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -61,7 +61,7 @@ jobs:
       - name: Install project and documentation dependencies
         run: |
           .venv\Scripts\Activate.ps1
-          pip install -r requirements/requirements_doc.txt -U
+          pip install --no-cache-dir -r requirements/requirements_doc.txt
 
       # Use environment variable to keep the doctree and avoid redundant build for PDF pages
       - name: Create HTML documentation
@@ -70,13 +70,13 @@ jobs:
           SPHINXBUILD_KEEP_DOCTREEDIR: "1"
         run: |
           .venv\Scripts\Activate.ps1
-          . .\doc\make.bat html
+          . .\doc\make.bat html 6>&1 2>&1 | Tee-Object -Variable output
 
-      - name: Check on failures
-        if: steps.create_html.outcome != 'success'
-        run: |
-          echo "Sphinx build failed, stopping the workflow."
-          exit 1
+          # Check sphinx-build exit code and error messages
+          if ($LASTEXITCODE -ne 0 -or $output -match 'CellExecutionError') {
+            Write-Error "HTML build failed, stopping the workflow."
+            exit 1
+          }
 
       - name: Upload HTML documentation artifact
         uses: actions/upload-artifact@v4
